name: CICD_pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: /usr/local/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#            distribution: 'adopt'
#            java-version: ${{ env.JDK_VERSION }}

#      - name: Cache Gradle packages
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#            restore-keys: ${{ runner.os }}-gradle

#      - name: Set up Android SDK
#        uses: android-actions/setup-android@v2
#        with:
#            api-level: ${{ env.SDK_VERSION }}
#            cache: yes
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Run Lint
#        run: ./gradlew lintDebug
#
#      - name: Upload lint html test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html
      - name: Set up Android SDK
        run: echo skipp


  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: /usr/local/android-sdk

    steps:
      - name: Set up Android SDK
        run: echo skipp
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: ${{ env.JDK_VERSION }}
#
#      - name: Set up Android SDK
#        uses: android-actions/setup-android@v2
#        with:
#          api-level: ${{ env.SDK_VERSION }}
#          cache: yes
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Run unit tests
#        run: ./gradlew test
#
#      - name: Upload unit test report
#        uses: actions/upload-artifact@v2
#        with:
#          name: unit_test_report
#          path: app/build/reports/tests/testDebugUnitTest/


  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: $HOME/Library/Android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Install JAXB
        run: |
          sdkmanager "extras;oracle;m2repository"
          mkdir -p $HOME/.m2/repository/com/sun/xml/bind
          cp -r $ANDROID_HOME/extras/oracle/m2repository/com/sun/xml/bind/* $HOME/.m2/repository/com/sun/xml/bind/

      - name: Set up Android SDK
        run: |
          brew install --cask android-sdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-${{ env.SDK_VERSION }}" "build-tools;${{ env.SDK_VERSION }}.0.0"


#      - name: Start emulator
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#         api-level: ${{ env.SDK_VERSION }}
#          target: google_apis
#          arch: x86_64
#          profile: Nexus 5X
#          script: ./gradlew connectedAndroidTest
#          disable-animations: true
#          emulator-options: -no-boot-anim -no-window
#          working-directory: ${{ github.workspace }}
#          adb-install-timeout-minutes: 8
#          boot-timeout-minutes: 8

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew connectedCheck

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: UI_test_report
          path: app/build/reports/androidTests/connected/


  build:
    needs: [instrumentation-test]
    name: Generate APK
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: /usr/local/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.SDK_VERSION }}
          cache: yes


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}


      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: shopping-list.apk
          path: app/build/outputs/apk/debug/app-debug.apk

