name: CICD_pipeline
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: /usr/local/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: ${{ env.JDK_VERSION }}


      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
            api-level: ${{ env.SDK_VERSION }}
            cache: yes

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload lint html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: /usr/local/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.SDK_VERSION }}
          cache: yes

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumented-test:
     needs: [ unit-test ]
     runs-on: windows-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: windows
          emulator: true


      - name: Install Android SDK and System Image
        run: |
          sdkmanager --install "system-images;android-29;default;x86_64"
          sdkmanager --install "platforms;android-29"
          sdkmanager --install "platform-tools"
          sdkmanager --install "emulator"
      
      - name: Download dependencies
        run: ./gradlew build --stacktrace

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-29;default;x86_64" --device "Nexus 5X"

      - name: Set environment variables
        run: |
          echo "ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL=60" >> $Env:GITHUB_ENV
      
      - name: Start emulator
        run: |
          Start-Process -FilePath "$env:ANDROID_SDK_ROOT\emulator\emulator.exe" -ArgumentList '-avd test -no-audio -no-window -no-boot-anim -gpu off' -NoNewWindow -PassThru
          Start-Sleep -Seconds 60
          adb wait-for-device
          adb shell input keyevent 82

      - name: Wait for emulator to finish booting
        run: |
          $bootanim=""
          $bootanim=$(adb -e shell getprop init.svc.bootanim)
          while ($bootanim -ne "stopped") {
            echo "Waiting for emulator to boot..."
            Start-Sleep -Seconds 5
            $bootanim=$(adb -e shell getprop init.svc.bootanim)
          }
          echo "Emulator booted successfully."

      - name: Run instrumented tests
        run: ./gradlew connectedAndroidTest
  
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
         name: UI_test_report
         path: app/build/reports/androidTests/connected/
          
  build:
    needs: [instrumented-test]
    name: Generate APK
    runs-on: ubuntu-latest

    env:
      SDK_VERSION: 33
      JDK_VERSION: 17
      ANDROID_HOME: /usr/local/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.SDK_VERSION }}
          cache: yes


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}


      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: shopping-list.apk
          path: app/build/outputs/apk/debug/app-debug.apk

